project:
  type: book

book:
  title: "Log Gaussian Cox Processes and INLA: Theory and Application"
  author: "Max Savery"
  date: "22/05/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - theory.qmd
    - inla_inlabru_tutorial_netherlands_data.qmd
    - inla_inlabru_lgcp_tutorial_netherlands_data.qmd
    #- summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    auto-stretch: false

execute:
  freeze: true

