project:
  type: book

book:
  title: "INLA and Log Gaussian Cox Processes: Theory and Application"
  author: "Max Savery"
  date: "18/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - theory.qmd
    - inla_inlabru_tutorial_netherlands_data.qmd
    - inla_inlabru_lgcp_tutorial_netherlands_data.qmd
    #- summary.qmd
    #- references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

execute:
  freeze: true

