# Introduction

This is a blog post about Log-Gaussian Cox Processes (LGCP). It is a follow up to the earlier blog post I made about Poisson Point Process models. In fact, the LGCP is an extension of the Poisson Point Process, in that a latent correlation structure is included in the point process model. Specifically, the LGCP uses a Gaussian Random Field to characterize the intensity of the point process. Doing so allows us to take into account spatial or temporal correlation across our region or period of interest. Statistically,  this is quite an advantageous improvement from the Poisson Point Process where spatial correlation could only be accounted for via covariates. However, the inclusion of the random field presents mathematical and computational challenges. We will address these challenges here, making use of the Integrated Nested Laplace Approximation (INLA) approach.

The general structure of this post is as follows: I will first introduce the LGCP, but only briefly, as most of the theory is the same for the Poisson Process as the LGCP. Then, I'll spend some time covering the INLA method and the accompanying R packages, ```INLA``` and ```inlabru```. I'll compare these packages for fitting models of continuous measures and, of course, point processes. At some point I will end the post and continue later with another about fitting multiple likelihood models in ```inla```, such as for the purpose of accounting for preferential sampling.

The reason I am writing about this is because having a model that incorporates spatial (or temporal) correlation via the Gaussian field is necessary to properly model both point processes (such as the Presence-only data of the last blog) or continuous measures in spatial-temporal intervals (such as air pollution). Not including correlation via the GF means that you then assume the covariates included in your model are sufficient to account for spatial fluctuations in the measurement. The problem with this is that is there no direct mechanism to relate the behavior of the process at one location to the behavior at another location. The GF does exactly this, taking into account the spatial dependence between measurement locations. 

So this is a more technical topic. The only thing we want to do is include spatial dependence, but we have to first learn a whole new method of approximation and software framework to be able to do so. However, the advantage is the INLA method/software is sufficiently general so that we can tackle a whole set of spatial-temporal modelling problems using the same approach. In fact, the INLA approach allows us to work with both continuous, discrete, and point-type data, and to combine the likelihoods of different datasets as long as the underlying process shares a set of parameters. That is really useful!